# Name of this Workflow
name: Build PineTime Firmware in docker container

# When to run this Workflow...
on:

  # Run this Workflow when files are updated (Pushed) in the "master" and "develop" Branch
  push:
    branches: [ master, develop ]

  # Also run this Workflow when a Pull Request is created or updated in the "master" and "develop" Branch
  pull_request:
    branches: [ master, develop ]

# Steps to run for the Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pfeerick/infinitime-build:latest
      options: -v /home/runner/work/InfiniTime/InfiniTime:/sources/:rw
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: BuildInfiniTime
        if: always()
        run: /opt/build.sh
          